### ISSUE TITLE
자가진단 설문에 추가해야 하는 기능

### ISSUE THREAD

**Issue by Ojongseok** [Kusithm-HDmedi-Team-C/Android#14]
### Description
자가진단 설문에 추가해야 하는 기능

## To-Do
- [ ] 자가진단 설문 화면 첫 진입 시 슬라이드해야 넘어간다는 설명 추가
- [ ] 답변 선택하지 않아도 이전 문항은 볼 수 있도록 수정
- [x] 설문 결과로 전환할 때 애니메이션

## ETC
- ViewPager2에서 오른쪽/왼쪽 스와이프 설정은 당장은 힘들어 보임...
