### ISSUE TITLE
자가진단 결과 화면 작업

### ISSUE THREAD

**Issue by seunghee17** [Kusithm-HDmedi-Team-C/Android#16]
## Description
자가진단 결과 화면 및 기능 작업

## To-Do
- [x] 점수 받아오는 과정 오류 수정
- [x] fragmentB 디자인 완료
- [x] 결과화면 갤러리 저장기능

## ETC
- 참고사항

**Comment by Ojongseok** [comment]
자가진단 설문을 마치고 진단결과 화면으로 이동할 떄 점수 합산을 intent에 담아서 보내주면 될까요??

**Comment by seunghee17** [comment]
점수를 보여주는 화면은 fragment라서 혹시 viewmodel에서 map을 정의해놓고 map에 점수들 저장할 수 있을까요? api명세서의 requestbody와 같은 데이터 형식이 필요해서요!
